# Generated by Django 4.1.1 on 2022-09-12 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('height', models.CharField(max_length=6)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(default=None, max_length=500)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_captain', models.BooleanField(default=False)),
                ('is_player', models.BooleanField(default=True)),
                ('is_guest', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
