# Generated by Django 4.1.1 on 2022-09-14 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_player_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
